version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=wilhelm357_
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=gym_app_db_new_v3
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"